server:
  port: 8036

spring:
  application:
    name: springcloud-feign-hystrix

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8021/eureka/

feign:
  hystrix:
    enabled: true
