server:
  port: 8021

eureka:
  instance:
    hostname: peer1
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://peer2:8022/eureka/,http://peer3:8023/eureka/
  server:
    # 关闭自我保护模式（缺省为打开：将失效的服务实例的注册信息保护起来，不予剔除）
    enable-self-preservation: false
    # 失效剔除间隔时间单位为ms（缺省为60*1000ms），服务失效后1秒就剔除
    eviction-interval-timer-in-ms: 1000

spring:
  application:
    name: springcloud-eureka-server
  profiles:
    active: 1