server:
  port: 8023

eureka:
  instance:
    hostname: peer3
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://peer2:8022/eureka/,http://peer1:8021/eureka/

spring:
  application:
    name: springcloud-eureka-server
  profiles:
    active: 3